name: GymTrack
options:
  bundleIdPrefix: com.avanian
  deploymentTarget:
    iOS: "18.0"

packages:
  GymTrackKit:
    path: ../GymTrackKit

targets:
  GymTrack:
    type: application
    platform: iOS
    sources:
      - GymTrack
    dependencies:
      - package: GymTrackKit
    settings:
      base:
        INFOPLIST_FILE: GymTrack/Info.plist
        CODE_SIGN_ENTITLEMENTS: GymTrack/GymTrack.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.avanian.gymtrack
    entitlements:
      path: GymTrack/GymTrack.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.avanian.gymtrack
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.avanian.gymtrack
        com.apple.developer.icloud-services:
          - CloudDocuments
    capabilities:
      HealthKit: true
      iCloud:
        services:
          - icloud-documents
        containerIdentifiers:
          - iCloud.com.avanian.gymtrack

  GymTrackTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - GymTrackTests
    dependencies:
      - target: GymTrack
